apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: root
          ports:
            - name: mongoexpress
              containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
  namespace: mongodb
spec:
  selector:
    app: mongoexpress
  ports:
    - name: mongoexpress
      protocol: TCP
      port: 8081
      targetPort: 8081