apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
data:
  root-password: cm9vdA==
  user-password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: mysql
data:
  mysql-database: mysqldb
  mysql-user: user
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: mysql-user
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql/
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
        
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306