apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: mysql
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service.mysql.svc.cluster.local
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: mysql
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 3312
      targetPort: 80
      nodePort: 30002