dbt_kube:
  outputs:
    dev:
      dbname: dbtkube
      host: postgresql.postgresql.svc.cluster.local
      pass: password
      port: 5432
      schema: kubeschema
      threads: 1
      type: postgres
      user: postgres
  target: dev