apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-job
spec:
  template:
    spec:
      containers:
        - name: dbt
          image: dbt-kube
          command: ["/bin/bash", "-c", "dbt run"]
          imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 2