apiVersion: v1
kind: Pod
metadata:
  name: pyspark-pod
  labels:
    app: pyspark
spec:
  containers:
    - name: pyspark
      image: pyspark
      command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
      imagePullPolicy: Never