apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  serviceAccountName: shell-sa
  containers:
    - name: ubuntu
      image: ubuntu-ssh
      command:
      - "/bin/bash"
      - "-c"
      args:
      - |
        service ssh restart
        env > /.kubenv
        echo 'export $(xargs < /.kubenv)' >> /root/.bashrc
        while true; do sleep 3600; done;
      imagePullPolicy: Never
      ports:
        - name: ssh
          containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu
  ports:
    - name: ubuntu
      protocol: TCP
      port: 22
      targetPort: 22